### PR TITLE
Bump Gerrit plugin API to 2.16.2

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Review by lucamilanesio — CHANGES_REQUESTED** [review]
If we move to Bazel build, we do not need this change at all.

**Comment by davido** [comment]
Right. I was not sure, though if plugin author agree with deletion of sbt driven build. So my plan was to maintain both build tool chains for a while: sbt and bazel.

**Comment by lucamilanesio** [comment]
> Right. I was not sure, though if plugin author agree with deletion of sbt driven build. So my plan was to maintain both build tool chains for a while: sbt and bazel.

IMHO maintaining both is going to be problematic for keeping them in sync. If the author doesn't agree with moving to Bazel, then it should stay with SBT. We do have an sbt template for building on the CI anyway.

**Comment by davido** [comment]
Moved to googlesource.com.

**Pull request closed without merging**
