### PR TITLE
Implement Bazel build

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Review by lucamilanesio — COMMENTED** [review]
We should remove as well the SBT build, isn't it?
Additionally, we should first create a stable branch for Gerrit 2.13 keeping the SBT build.

**Comment by davido** [comment]
It seems that some transitive dependencies are still missing, at least: "joda-time:joda-time:jar:2.9.9", "org.apache.velocity:velocity:jar:1.7" and "commons-collections:commons-collections:jar:3.2.2".

**Comment by davido** [comment]
It worth noting, that the build tool chain for this plugin depends on the target branch. That's because some of the dependencies were removed from gerrit core:

* velocity
* commons-collections
* joda-time

**Comment by davido** [comment]
Moved to googlesource.com.

**Pull request closed without merging**
