### PR TITLE
Update external dependencies

### PR DESCRIPTION
**Pull request by davido**
Update pac4j to 3.4.0.

### CODE REVIEW

**Review by lucamilanesio — APPROVED** [review]

**Comment by thesamet** [comment]
Thanks for the PRs, @davido. I'm currently on vacation and will take a look in a couple of weeks.

**Comment by jhansche** [comment]
@davido FYI, I rebuilt the plugin using most of your PR commits, but I still had some issues, where the `?client_name=SAML2Client` was causing the redirect validator to fail.

I had to revert the client dependency back to version `2.0.0` to get it working again.  I also had to comment out the `commons-collections` and `org.apache.velocity` exclusions, because those dependencies seem to be no longer accessible to the plugin.

I'm sure that isn't the best approach, but it's what I had to do to get our Gerrit instance back up and running again.

**Comment by davido** [comment]
@jhansche Thanks for your feedback.

> I rebuilt the plugin using most of your PR commits, but I still had some issues, where the ?client_name=SAML2Client was causing the redirect validator to fail.

Can you provide more details on the failure? Are you aware of this thread on developer mailing list: [1].

@mikelupo mentioned there, that he had to adjust server side code to reflect the changes caused by `pac4j` upgrade. Can you paste here exactly, what server side changes you made to make it work? And what was the problem without your server side changes?

> I had to revert the client dependency back to version 2.0.0 to get it working again. I also had to comment out the commons-collections and org.apache.velocity exclusions, because those dependencies seem to be no longer accessible to the plugin.

That's correct. You havn't mentioned what Gerrit version you are using, but `velocity` was removed in recent Gerrit versions (with its transitive dependency `commons-collections`), so that this transitive dependency of `pac4j` must be re-added to make the plugin work against recent Gerrit versions. I did it in Bazel build implementation in a separate commit: [2].

[1] https://groups.google.com/d/topic/repo-discuss/FPfy_Ng8eGQ/discussion
[2] https://github.com/thesamet/gerrit-saml-plugin/pull/20/commits/2b4010ea52237b2c150804d0c3d79f0f8f68ea51

**Comment by mikelupo** [comment]
@davido, @jhansche,
The corporate server side person is in India. I have no direct visibility into the server side changes. All I know is that they had to change the expected metadata to match mine. Which included the redirect URL with the ? parameter part of the uri.

**Comment by davido** [comment]
Thanks, for update @mikelupo. When saying server side changes, what do you mean exactly? Gerrit oder IdP? Can you ask the guys what did they change exactly to make the plugin work with `pac4j` 3.4.0?

**Comment by mikelupo** [comment]
@davido, I emailed the server guy. All he says is that they had to update the Application metadata on the server-side to match what the client was sending. Namely, this line from the idP metadata: HTTP-POST" Location="https://gerrit.mycompanycom/gerrit/plugins/gerrit-saml-plugin/saml?client_name=SAML2Client&logoutendpoint=true"/> 

Originally, before the update, it was: (no uri parameter part)
HTTP-POST" Location="https://gerrit.mycompanycom/gerrit/plugins/gerrit-saml-plugin/saml"/>

**Comment by jhansche** [comment]
@davido Looking through the above linked thread now.
Yes, it looks like @mikelupo was having the same error I was, with the `?client_name=..` being expected but not provided by the IdP (and therefore Gerrit/plugin was refusing to accept the redirected login data because the URI didn't match exactly).

It would be great to find out what was necessary to fix that and get that updated so that we can use the latest version -- not sure what benefits that brings, but generally speaking newer is better. It sounds like we'll have to time that just right so that I replace the plugin with the updated 3.4.0 version at the same time as my ops team updating the IdP configuration. Do you know if it would be possible to update the IdP config first and will the 2.0.0 version ignore the extra URL query params?

I didn't have the luxury of waiting for someone with access to our IdP system (and whatever that entails), because the saml plugin breaking was unexpected. I had to hack it together to fix what I could as quickly as possible 🤦

**Comment by davido** [comment]
@jhansche @mikelupo Thanks for the feedback.

According to the: [1] in pac4j v3 `client_name` parameter in the callback is mandatory. So I think the migration from plugin that uses v2  to plugin with pac4j v3 is as easy as to change the callback URL to:

```
https://gerrit.mycompany.com/plugins/gerrit-saml-plugin/saml?client_name=SAML2Client
```

A good question indeed, if for backward compatbility you could adapt callback URL on IdP side and still try to use plugin with pac4j version 2.0.0? @jhansche Do you have staging Gerrit + IdP insance and could try it? Or may be @leleuj can comment on that question?

[1] https://github.com/pac4j/pac4j/blob/master/documentation/blog/understanding-the-callback-endpoint.md

**Comment by jhansche** [comment]
I don't have a staging setup to test with. But I could ask my ops team to experiment with it for now, and if it doesn't work we can just revert it pretty quickly. We use Okta for IdP.

**Comment by davido** [comment]
> But I could ask my ops team to experiment with it for now, and if it doesn't work we can just revert it pretty quickly.

@jhansche Thanks, that would be great!

**Comment by leleuj** [comment]
Regarding the callback URL and the SAML support, things have changed between the versions 2 and 3 of pac4j.
In pac4j v2, at the initialization of the `SAML2Client`, the callback URL, for example: `http://localhost:8080/callback` was turned into `http://localhost:8080/callback?client_name=SAML2Client` and the SAML metadata were generated with that value (`http://localhost:8080/callback?client_name=SAML2Client`) as the entityID.

In pac4j v3, at the initialization of the `SAML2Client`, the callback URL is no longer touched and the appropriate callback URL is computed on demand: either `http://localhost:8080/callback?client_name=SAML2Client` or `http://localhost:8080/callback/SAML2Client` so the SAML metadata use the original value (`http://localhost:8080/callback`)  as the entityID. This may cause issue. Nonetheless, you can force this entityID value in the SAML2 configuration with: `cfg.setServiceProviderEntityId("http://localhost:8080/callback?client_name=SAML2Client");`

This callback URL values are for the login process. It's generally called the ACS (Assertion Consumer Service) URL.

To handle SAML logout requests, the same URL is used with an extra parameter: `logoutendpoint=true` to notify it deals with logouts.

Hope it makes things clearer...

**Comment by davido** [comment]
@leleuj Thanks, it does help. Another issue I had with `pac4j` v2 to `pac4j` v3 migration is NPE exception during initialization time, that I mentioned in https://github.com/pac4j/pac4j/issues/1210.

Could you clarify, what do we have to pass to `client.setServiceProviderMetadataFilepath("sp-metadata.xml")`? I'm asking because it wasn't set in `pac4j` v2.0? Or is this problem is going to be fixed shortly?

Thanks.

**Comment by leleuj** [comment]
The `setServiceProviderMetadataFilepath` method allows you to define the name (and path) of the file in which the service provider (the application ) metadata will be generated. Generally, it's mandatory as you need to upload these metadata to the IdP you want to integrate with.

I'm not sure if this is a big change or not which can go into a v3.5.0 release. I'll take a look at it in priority.

**Comment by davido** [comment]
@leleuj Got it, thank you!

**Comment by davido** [comment]
> This callback URL values are for the login process. It's generally called the ACS (Assertion Consumer Service) URL.

@leleuj Hopefully I understood you correctly in this change:

https://gerrit-review.googlesource.com/c/plugins/saml/+/209233 Adapt assertion consumer service URL setting to pacj4 v3

Basically I'm setting now both:

```java
String callbackUrl = "http://localhost:8080/plugins/gerrit-saml-plugin/saml";

samlClientConfig.setServiceProviderEntityId(callbackUrl + "?client_name=SAML2Client");
saml2Client.setCallbackUrl(callbackUrl);
```

**Comment by davido** [comment]
@leleuj It works all as expected in `pac4j` 3.4.0.

As you pointed out, for logout, I'm now passing: "http://localhost:8081/plugins/gerrit-saml-plugin/saml?client_name=SAML2Client&logoutendpoint=true"

in that case the code is throwing HttpAction.ok exception:

```
  @Override
    public SAML2Credentials extract(final WebContext context) {
        final boolean logoutEndpoint = context.getRequestParameter(SAML2ServiceProviderMetadataResolver.LOGOUT_ENDPOINT_PARAMETER) != null;
        final SAML2MessageContext samlContext = this.contextProvider.buildContext(context);
        if (logoutEndpoint) {
            // SAML logout request/response
            this.logoutProfileHandler.receive(samlContext);

            // return a logout response if necessary
            final LogoutResponse logoutResponse = this.saml2LogoutResponseBuilder.build(samlContext);
            this.saml2LogoutResponseMessageSender.sendMessage(samlContext, logoutResponse, null);

            final Pac4jSAMLResponse adapter = samlContext.getProfileRequestContextOutboundMessageTransportResponse();
            if (spLogoutResponseBindingType.equalsIgnoreCase(SAMLConstants.SAML2_POST_BINDING_URI)) {
                final String content = adapter.getOutgoingContent();
                throw HttpAction.ok(context, content);
            } else {
                final String location = adapter.getRedirectUrl();
                throw HttpAction.redirect(context, location);
            }
        } else {
            // SAML authn response
            final SAML2Credentials credentials = (SAML2Credentials) this.profileHandler.receive(samlContext);
            return credentials;
        }
    }
```

that I have to do something with. Current code was just re-throwing, so that I adjusted it:

```
try {
      if (isSamlPostback(httpRequest)) {
        J2EContext context = new J2EContext(httpRequest, httpResponse);
        signin(context);
      } else if (isGerritLogin(httpRequest)) {
        if (user == null) {
          J2EContext context = new J2EContext(httpRequest, httpResponse);
          redirectToIdentityProvider(context);
        } else {
          HttpServletRequest req = new AuthenticatedHttpRequest(httpRequest, user);
          chain.doFilter(req, response);
        }
      } else if (isGerritLogout(httpRequest)) {
        httpRequest.getSession().removeAttribute(SESSION_ATTR_USER);
        chain.doFilter(httpRequest, httpResponse);
      } else {
        chain.doFilter(httpRequest, httpResponse);
      }
    } catch (final HttpAction httpAction) {
        // It's OK that HttpAction.ok() is thrown in logout logic case
    	if (httpAction.getCode() != 200) {    	
    		throw new TechnicalException("Unexpected HTTP action", httpAction);
    	}
    }
```

Is this new logout flow? How it worked in pac4j 2.0?

**Comment by leleuj** [comment]
The logout support (let's say SLO for Single Log Out) is new to pac4j v3.4.0. In v3.3.0, SAML logout requests were just ignored. In previous versions, there was an error.

The callback URL with "logoutendpoint=true" is meant to receive SAML logout requests (`<samlp:LogoutRequest`) and it replies a SAML logout response. If the POST binding (by default) is used for logout, this response is posted to the IdP, thus the `throw HttpAction.ok(context, content);`. And it's a `throw` as this happens during the credentials extraction. In fact, we expect to extract credentials in a login process, but if we notice it's a logout, we build the response and break the regular flow to return it.

So yes, finally, you need to catch it and consider it OK (as things have already been performed on the request). Things will be slightly different in pac4j v4.

**Comment by thesamet** [comment]
Project discontinued. See https://github.com/thesamet/gerrit-saml-plugin/

**Pull request closed without merging**
